### ISSUE TITLE
🕰 Zeitplan auf Podium Scroll Overflow ("Nach 10.06. fixen")

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-expo#131]
Wegen der Studi-Infotage vorweg der Wunsch "gravierende Änderungen bitte nicht vor dem 10.06. fixen"

Der Zeitplan des Podiums hat bei vielen Einträgen dafür gesorgt, dass diese nicht komplett dargestellt werden. (Letzter Eintrag in der linken Spalte abgeschnitten) Betrifft Vorlage 2.

Als Workaround wurden die folgenden (unschönen) Zeilen als Custom-CSS eingefügt:
```css
.postid-191694 foreignObject .schedule .schedule-content{
    height: 685px !important;
}
```

Custom CSS sollte nach dem Fix entfernt werden.

Nähere Details & Betroffenes Podium unter 🎫 http://go.fau.de/9svs-
